/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package diet.task.mazegame.server;

import diet.server.ConversationController.CCMAZE_EDI_2014_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE;
import diet.server.ConversationController.CCMAZE_UWA2013_DYADIC_4PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE;
import diet.server.ConversationController.CCMAZE_UWA2013_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE;
import diet.server.ConversationController.CCMAZE_UWA2013_DYADIC_MULTI_4_PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE_DEPRECATED;
import diet.server.ConversationController.DefaultConversationController;
import javax.swing.SwingUtilities;

/**
 *
 * @author sre
 */
public class JMazeGameControlFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    //CCMAZE_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE cC;
     DefaultConversationController cC;
    
    
    public JMazeGameControlFrame(DefaultConversationController cC, String title) {
        super(title);
        initComponents();
        this.cC=cC;
        this.jProgressBar1.setStringPainted(true);
    }

    public void updatePartnerNumber(final int partnernumber){
        SwingUtilities.invokeLater(new Runnable(){
             public void run(){
                  jLabel4.setText(""+partnernumber);
             }
        });
    }
    
    public void updateJProgressBar(final int value, final String text){
        SwingUtilities.invokeLater(new Runnable(){
             public void run(){
                  jProgressBar1.setValue(value);
                  jProgressBar1.setString(text);
                  //jProgressBar1.setName(text);       
                  
             }
        });
        
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Partner/ maze  no:");

        jLabel4.setText("1");

        jButton3.setText("+10");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("- 10");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Pause");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("+1");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jTextPane1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jScrollPane1.setViewportView(jTextPane1);

        jToggleButton1.setText("START");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jButton7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cC.getC().sendArtificialTurnToAllParticipants(jTextPane1.getText(), 0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try{
          int value = Integer.parseInt(jLabel4.getText());
          if(cC instanceof CCMAZE_UWA2013_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE){
              ((CCMAZE_UWA2013_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) cC).performSwap(value+1, value);
          }
          if(cC instanceof CCMAZE_UWA2013_DYADIC_4PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) {
             
              ((CCMAZE_UWA2013_DYADIC_4PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) cC).performSwap(value+1, value);
              
          }
         if(cC instanceof CCMAZE_UWA2013_DYADIC_MULTI_4_PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE_DEPRECATED ) {
             
             ((CCMAZE_UWA2013_DYADIC_MULTI_4_PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE_DEPRECATED ) cC).nextMazeCALLEDFROMUI();
         }
         if (cC instanceof CCMAZE_EDI_2014_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE){
             ((CCMAZE_EDI_2014_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE)cC).performSwap(value+1, value);
         }
         
         
          
        }catch (Exception e){
            e.printStackTrace();
        }
        
       
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(cC instanceof CCMAZE_UWA2013_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) ((CCMAZE_UWA2013_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) cC).addTimeToClock(10000);
        if(cC instanceof CCMAZE_UWA2013_DYADIC_4PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) ((CCMAZE_UWA2013_DYADIC_4PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) cC).addTimeToClock(10000);
        if(cC instanceof CCMAZE_UWA2013_DYADIC_MULTI_4_PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE_DEPRECATED)((CCMAZE_UWA2013_DYADIC_MULTI_4_PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE_DEPRECATED)cC).addTimeToClock(10000);
         if (cC instanceof CCMAZE_EDI_2014_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE){((CCMAZE_EDI_2014_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE)cC).addTimeToClock(10000);
         }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       if(cC instanceof CCMAZE_UWA2013_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) ((CCMAZE_UWA2013_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) cC).pauseTimer();
       if(cC instanceof CCMAZE_UWA2013_DYADIC_4PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) ((CCMAZE_UWA2013_DYADIC_4PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) cC).pauseTimer();
       if(cC instanceof CCMAZE_UWA2013_DYADIC_MULTI_4_PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE_DEPRECATED)((CCMAZE_UWA2013_DYADIC_MULTI_4_PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE_DEPRECATED)cC).pauseTimer();
       if (cC instanceof CCMAZE_EDI_2014_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE){((CCMAZE_EDI_2014_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE)cC).pauseTimer();}
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        jToggleButton1.setEnabled(false);
        jToggleButton1.setText("");
        if(cC instanceof CCMAZE_UWA2013_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) ((CCMAZE_UWA2013_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) cC).startExperiment();
        if(cC instanceof CCMAZE_UWA2013_DYADIC_4PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) ((CCMAZE_UWA2013_DYADIC_4PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) cC).startExperiment();
        if(cC instanceof CCMAZE_UWA2013_DYADIC_MULTI_4_PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE_DEPRECATED)((CCMAZE_UWA2013_DYADIC_MULTI_4_PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE_DEPRECATED)cC).startExperiment();
         if (cC instanceof CCMAZE_EDI_2014_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE){((CCMAZE_EDI_2014_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE)cC).startExperiment();}
       
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if(cC instanceof CCMAZE_UWA2013_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) ((CCMAZE_UWA2013_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) cC).addTimeToClock(-10000);
        if(cC instanceof CCMAZE_UWA2013_DYADIC_4PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) ((CCMAZE_UWA2013_DYADIC_4PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE) cC).addTimeToClock(-10000);
        if(cC instanceof CCMAZE_UWA2013_DYADIC_MULTI_4_PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE_DEPRECATED)((CCMAZE_UWA2013_DYADIC_MULTI_4_PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE_DEPRECATED)cC).addTimeToClock(-10000);
         if (cC instanceof CCMAZE_EDI_2014_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE){((CCMAZE_EDI_2014_DYADIC_8PARTICIPANTS_SEPARATE_DYADS_MAZEBYMAZE)cC).addTimeToClock(-10000);}
       
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMazeGameControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMazeGameControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMazeGameControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMazeGameControlFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JMazeGameControlFrame(null,"").setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
