/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cornell.mchci;

import diet.server.Conversation;
import diet.server.Participant;
import javax.swing.JRadioButton;
import javax.swing.*;
import java.util.*;

/**
 *
 * @author dhau
 */
public class SurveyJFrame extends javax.swing.JFrame {
    Conversation c;
    Participant p;
    JLabel[] questions;
    JButton submitButton;
    ArrayList allRadioButtons;
    
    /**
     * Creates new form SurveyJFrame
     */
    public SurveyJFrame(Conversation c, Participant p) {
          
        this.c = c;
        this.p = p;
        questions = new javax.swing.JLabel[] {
           new JLabel("What is this?"), 
           new JLabel("Where am I?"), 
           new JLabel("What year is this?"), 
           new JLabel("Help, I'm trapped in a computer!")};
        submitButton = new JButton();
        submitButton.setText("Submit");
        allRadioButtons = new ArrayList();
        
        for (JLabel question : questions) {
            add(question);
        }
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        
        add(questions[0]);
        add(questions[1]);
        add(submitButton);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30,30,30)
                .addGroup(layout.createParallelGroup()
                    .addComponent(submitButton)
                    .addComponent(questions[0])
                    .addComponent(questions[1]))
                .addGap(30,30,30)
            )
        );
        
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(questions[0])
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(questions[1])
                .addComponent(submitButton)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        
        pack();
        
        
    }
    
    //Add buttons to an array of buttons
    //Return index
    
    
//    public ButtonGroup newLikertButtonGroup(int numOptions){
//        JRadioButton[] newButtonGroup = new JRadioButton[numOptions];
//        for(int j = 0; j < numOptions; j++){
//            JRadioButton newButton = new JRadioButton();
//            newButton.setText(Integer.toString(j));
//            newButtonGroup[j] = newButton;
//        }
//        return newButtonGroup;
//    }
    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SurveyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SurveyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SurveyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SurveyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new SurveyJFrame().setVisible(true);
            }
        });
    }

    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables



//        buttonGroup1 = new javax.swing.ButtonGroup();
//        jLabel1 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jRadioButton1 = new javax.swing.JRadioButton();
//        jRadioButton2 = new javax.swing.JRadioButton();
//        jButton1 = new javax.swing.JButton();
//        jRadioButton3 = new javax.swing.JRadioButton();
//        jRadioButton4 = new javax.swing.JRadioButton();
//        jRadioButton5 = new javax.swing.JRadioButton();
//        jRadioButton6 = new javax.swing.JRadioButton();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jLabel1.setText("How hardworking do you think your partner is?");
//
//        jLabel2.setText("How angry are you?");
//
//        buttonGroup1.add(jRadioButton1);
//        jRadioButton1.setText("1");
//        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jRadioButton1ActionPerformed(evt);
//            }
//        });
//
//        buttonGroup1.add(jRadioButton2);
//        jRadioButton2.setText("2");
//        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jRadioButton2ActionPerformed(evt);
//            }
//        });
//
//        jButton1.setText("Submit");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        buttonGroup1.add(jRadioButton3);
//        jRadioButton3.setText("3");
//        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jRadioButton3ActionPerformed(evt);
//            }
//        });
//
//        buttonGroup1.add(jRadioButton4);
//        jRadioButton4.setText("4");
//        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jRadioButton4ActionPerformed(evt);
//            }
//        });
//
//        buttonGroup1.add(jRadioButton5);
//        jRadioButton5.setText("5");
//        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jRadioButton5ActionPerformed(evt);
//            }
//        });
//
//        buttonGroup1.add(jRadioButton6);
//        jRadioButton6.setText("6");
//        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jRadioButton6ActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(30, 30, 30)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jButton1)
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jRadioButton1)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jRadioButton2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jRadioButton3)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jRadioButton4)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jRadioButton5)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jRadioButton6))
//                    .addComponent(jLabel2)
//                    .addComponent(jLabel1))
//                .addContainerGap(188, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGap(95, 95, 95)
//                .addComponent(jLabel2)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jLabel1)
//                .addGap(3, 3, 3)
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jRadioButton1)
//                    .addComponent(jRadioButton2)
//                    .addComponent(jRadioButton3)
//                    .addComponent(jRadioButton4)
//                    .addComponent(jRadioButton5)
//                    .addComponent(jRadioButton6))
//                .addGap(16, 16, 16)
//                .addComponent(jButton1)
//                .addContainerGap(181, Short.MAX_VALUE))
//        );
//        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        // TODO add your handling code here:
//        
//        javax.swing.JRadioButton jr = null;
//        for(JRadioButton jrb : getRadioButtons()){
//            if(jrb.isSelected()){
//                jr = jrb;
//            }
//        }
//        c.saveDataToConversationHistory("abc", "**SURVEY RESPONSE: " + p.getParticipantID()+ "** "  + jr.getText());
//        setVisible(false);
//    }
//